-- 코드를 작성해주세요
SELECT YEAR(a.DIFFERENTIATION_DATE) AS YEAR, (b.MAX_SIZE - a.SIZE_OF_COLONY) AS YEAR_DEV, a.ID
FROM ECOLI_DATA a 
LEFT JOIN (
    SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, MAX(A.SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA A
    GROUP BY YEAR(A.DIFFERENTIATION_DATE)
    ) b ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC