-- 코드를 입력하세요
SELECT USG.TITLE, USG.BOARD_ID, REP.REPLY_ID, REP.WRITER_ID, REP.CONTENTS, DATE_FORMAT(REP.CREATED_DATE, "%Y-%m-%d") "CREATED_DATE"
FROM USED_GOODS_BOARD USG
    INNER JOIN USED_GOODS_REPLY REP
    ON USG.BOARD_ID = REP.BOARD_ID
WHERE USG.CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-31"
ORDER BY REP.CREATED_DATE, USG.TITLE
