# .github/workflows/update-readme.yml

name: Update README

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run update.py
      run: python update.py

    # --- 여기서부터 확인 및 수정 ---
    - name: Commit and Push if changed
      # 'run:' 키워드보다 아래 스크립트 전체가 더 들여쓰기 되어야 합니다.
      run: |
        git config --global user.name 'sjh1108'
        git config --global user.email 'ch6854@naver.com'
        # 'if' 문을 포함한 모든 스크립트 라인의 시작점은 동일해야 합니다.
        if ! git diff --quiet README.md; then
          echo "README.md has been updated. Committing changes."
          git add README.md
          git commit -m "docs: solved problem list auto-update"
          git push
        else
          echo "No changes detected in README.md. Skipping commit."
        fi